# Generated by Django 2.2.10 on 2020-08-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
