# Generated by Django 2.2.10 on 2020-08-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='passed_by_mentor',
            field=models.BooleanField(default=False),
        ),
    ]
