# Generated by Django 2.2.10 on 2020-08-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='acitve',
            field=models.BooleanField(default=True),
        ),
    ]
