# Generated by Django 2.2.10 on 2020-08-24 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_acitve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='acitve',
            new_name='active',
        ),
    ]
